/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Страница предстоящих встреч владельца.
         *
         *     Один список бронирований всех типов событий, отсортированный
         *     по `startsAt` по возрастанию. Каждая запись содержит краткую карточку
         *     типа события, поэтому дозапросы не нужны.
         */
        get: operations["AdminBookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создание бронирования гостем.
         *
         *     Шаг 4 публичного сценария гостя, завершающий: гость отправляет выбранный
         *     слот, своё имя и email. Аккаунт при этом не создаётся.
         *
         *     Проверки сервера:
         *
         *     - тип события существует, иначе 404 `not_found`;
         *     - `startsAt` совпадает с началом слота на сетке, иначе 409 `slot_not_in_grid`;
         *     - `startsAt` лежит в окне записи на 14 дней, иначе 409 `slot_out_of_window`;
         *     - время не пересекается с уже существующими бронированиями **любых** типов
         *     событий, иначе 409 `slot_taken`.
         *
         *     Ответ 409 `slot_taken` означает, что слот заняли между шагами 3 и 4:
         *     клиенту следует перезапросить календарь слотов и предложить другое время.
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список типов событий для страницы с видами брони.
         *
         *     Шаг 1 публичного сценария гостя.
         */
        get: operations["EventTypes_list"];
        put?: never;
        /**
         * @description Создание типа события владельцем.
         *
         *     Идентификатор задаёт сам владелец. Если тип с таким `id` уже есть,
         *     возвращается 409 `event_type_exists`.
         */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Карточка одного типа события.
         *
         *     Шаг 2 публичного сценария гостя: гость выбрал вид брони.
         */
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Календарь свободных слотов выбранного типа события.
         *
         *     Шаг 3 публичного сценария гостя. Слоты строятся по рабочему расписанию
         *     владельца с шагом `Owner.slotStepMinutes`; слот попадает в ответ, только
         *     если он полностью свободен — пересечения с бронированиями любых других
         *     типов событий исключают слот из выдачи.
         *
         *     Диапазон `from`–`to` должен целиком лежать в окне записи: от текущей даты
         *     до текущей даты плюс `Owner.bookingWindowDays` (14) дней. По умолчанию
         *     возвращается всё окно целиком. Диапазон вне окна — 400 `validation_failed`.
         */
        get: operations["EventTypes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Профиль владельца календаря и правила формирования слотов.
         *
         *     Используется публичной страницей бронирования (чей это календарь,
         *     в каком часовом поясе показывать время) и админской частью,
         *     которая работает от этого профиля по умолчанию.
         */
        get: operations["OwnerProfile_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Тело ответа при ошибке. */
        ApiError: {
            /** @description Код ошибки для обработки на клиенте. */
            code: components["schemas"]["ErrorCode"];
            /** @description Человекочитаемое сообщение. */
            message: string;
            /** @description Дополнительный контекст, например список невалидных полей. */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Бронирование — занятый слот календаря.
         *
         *     Бронирования всех типов событий живут в одном календаре: два бронирования
         *     не могут пересекаться по времени, даже если относятся к разным типам.
         */
        Booking: {
            /** @description Идентификатор бронирования, назначает сервер. */
            id: string;
            /** @description Тип события, на который создана запись. */
            eventType: components["schemas"]["EventTypeSummary"];
            /**
             * Format: date-time
             * @description Начало встречи, UTC.
             */
            startsAt: string;
            /**
             * Format: date-time
             * @description Конец встречи: `startsAt` + длительность типа события. Вычисляет сервер.
             */
            endsAt: string;
            /** @description Кто записался. */
            guest: components["schemas"]["Guest"];
            /** @description Комментарий гостя. */
            notes?: string;
            /**
             * Format: date-time
             * @description Момент создания записи.
             */
            createdAt: string;
        };
        /** @description Данные для создания бронирования. */
        BookingCreate: {
            /** @description Идентификатор выбранного типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало выбранного слота, UTC. Должно совпадать с одним из значений
             *     `Slot.startsAt`, полученных из календаря свободных слотов.
             */
            startsAt: string;
            /** @description Имя и email гостя. */
            guest: components["schemas"]["Guest"];
            /** @description Необязательный комментарий к встрече. */
            notes?: string;
        };
        /** @description Свободные слоты одного календарного дня в часовом поясе владельца. */
        DaySlots: {
            /**
             * Format: date
             * @description Дата в часовом поясе владельца.
             */
            date: string;
            /** @description Свободные слоты этого дня. Пустой массив означает, что записаться нельзя. */
            slots: components["schemas"]["Slot"][];
        };
        /**
         * @description Машиночитаемая причина отказа.
         * @enum {string}
         */
        ErrorCode: "validation_failed" | "not_found" | "event_type_exists" | "slot_taken" | "slot_not_in_grid" | "slot_out_of_window";
        /**
         * @description Тип события — вид встречи, который владелец предлагает гостям.
         *
         *     Гость видит название, описание и длительность; длительность задаёт,
         *     сколько времени занимает слот этого типа.
         */
        EventType: {
            /** @description Идентификатор, который задаёт владелец при создании. Уникален в пределах сервиса. */
            id: string;
            /** @description Название, например «Знакомство». */
            title: string;
            /** @description Описание для страницы с видами брони. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
            /**
             * Format: date-time
             * @description Момент создания типа события.
             */
            createdAt: string;
        };
        /** @description Данные для создания типа события. Поле `createdAt` заполняет сервер. */
        EventTypeCreate: {
            /** @description Идентификатор задаёт владелец. Если такой уже существует — 409 `event_type_exists`. */
            id: string;
            title: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Краткая карточка типа события внутри бронирования. */
        EventTypeSummary: {
            id: string;
            title: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Гость — человек, который бронирует встречу. Аккаунт не создаётся. */
        Guest: {
            /** @description Имя гостя. */
            name: string;
            /**
             * Format: email
             * @description Email гостя для связи и подтверждения.
             */
            email: string;
        };
        /**
         * @description Владелец календаря — единственный заранее заданный профиль.
         *
         *     Создаётся при развёртывании сервиса и через API не изменяется.
         *     Помимо контактных данных описывает сетку, по которой строятся слоты.
         */
        Owner: {
            /** @description Идентификатор профиля владельца. */
            id: string;
            /** @description Отображаемое имя, показывается гостю на странице бронирования. */
            name: string;
            /**
             * Format: email
             * @description Контактный адрес владельца.
             */
            email: string;
            /** @description Часовой пояс в формате IANA, например `Europe/Moscow`. */
            timeZone: string;
            /** @description Дни недели, в которые владелец принимает встречи. */
            workdays: components["schemas"]["Weekday"][];
            /** @description Начало рабочего дня, например `10:00`. */
            workDayStart: components["schemas"]["TimeOfDay"];
            /** @description Конец рабочего дня, например `18:00`. Последний слот заканчивается не позже этого времени. */
            workDayEnd: components["schemas"]["TimeOfDay"];
            /**
             * Format: int32
             * @description Шаг сетки слотов в минутах: начала слотов кратны этому значению от `workDayStart`.
             */
            slotStepMinutes: number;
            /**
             * Format: int32
             * @description Глубина окна записи в днях, считая от текущей даты. По умолчанию 14.
             */
            bookingWindowDays: number;
        };
        /**
         * @description Слот — отрезок времени на сетке владельца, доступный для записи.
         *
         *     Слоты не хранятся как отдельные записи: сервер вычисляет их из рабочего
         *     расписания владельца, длительности типа события и уже созданных броней.
         *     В ответах перечисляются только свободные слоты.
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота, UTC. Именно это значение гость отправляет при бронировании.
             */
            startsAt: string;
            /**
             * Format: date-time
             * @description Конец слота: `startsAt` + `EventType.durationMinutes`.
             */
            endsAt: string;
        };
        /** @description Календарь свободных слотов одного типа события за запрошенный диапазон дат. */
        SlotsPage: {
            /** @description Тип события, для которого построен календарь. */
            eventTypeId: string;
            /**
             * Format: int32
             * @description Длительность слота в минутах.
             */
            durationMinutes: number;
            /** @description Часовой пояс владельца, в котором сгруппированы дни. */
            timeZone: string;
            /**
             * Format: date
             * @description Первый день диапазона включительно.
             */
            from: string;
            /**
             * Format: date
             * @description Последний день диапазона включительно.
             */
            to: string;
            /** @description Дни диапазона по возрастанию, включая дни без свободных слотов. */
            days: components["schemas"]["DaySlots"][];
        };
        /** @description Время суток в формате `HH:mm` по часовому поясу владельца. */
        TimeOfDay: string;
        /**
         * @description День недели.
         * @enum {string}
         */
        Weekday: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AdminBookings_list: {
        parameters: {
            query?: {
                /** @description Нижняя граница выборки включительно, UTC. По умолчанию — текущий момент. */
                from?: string;
                /** @description Верхняя граница выборки исключительно, UTC. По умолчанию не ограничена. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description 400 — некорректный запрос. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description 201 — ресурс создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description 400 — некорректный запрос. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 409 — конфликт с текущим состоянием календаря. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description 201 — ресурс создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 400 — некорректный запрос. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 409 — конфликт с текущим состоянием календаря. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_listSlots: {
        parameters: {
            query?: {
                /** @description Первый день диапазона включительно. По умолчанию — текущая дата. */
                from?: string;
                /** @description Последний день диапазона включительно. По умолчанию — текущая дата плюс 14 дней. */
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsPage"];
                };
            };
            /** @description 400 — некорректный запрос. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    OwnerProfile_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
